{% set name = "qibolab" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibolab/archive/v{{ version }}.tar.gz
  sha256: 662ada8a4684a0e6f9c77275c024648f1286cd9f04f75d6c834595ddfad03f8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry
  run:
    - python >=3.8
    - qibo >=0.1.8
    - more-itertools
    - networkx
    - pyyaml

test:
  imports:
    - qibolab

about:
  home: https://github.com/qiboteam/qibolab
  summary: Quantum hardware module and drivers for Qibo
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
