{% set name = "qibolab" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibolab/archive/v{{ version }}.tar.gz
  sha256: 06bd448370dd316579a6c0232496336a23cd6b4418466b9af079a69bb26263dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.12
    - poetry
  run:
    - python >=3.8,<3.12
    - qibo >=0.1.8
    - more-itertools
    - networkx
    - pyyaml

test:
  imports:
    - qibolab

about:
  home: https://github.com/qiboteam/qibolab
  summary: Quantum hardware module and drivers for Qibo
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
