{% set name = "qibolab" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibolab/archive/v{{ version }}.tar.gz
  sha256: dfae0df43ae16e516503800517d895b68a0c9e159c56abde84eeff5f27649c97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.12
    - poetry
  run:
    - python >=3.8,<3.12
    - qibo >=0.1.8
    - more-itertools
    - networkx
    - pyyaml

test:
  imports:
    - qibolab

about:
  home: https://github.com/qiboteam/qibolab
  summary: Quantum hardware module and drivers for Qibo
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
